# SPDX-FileCopyrightText: 2021 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"


stages:
  - lint
  - test
  - prepare-release
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
include:
  - project: labs/salt-automation
    file: gitlab-ci-templates/common/autopub.v1.yml
  - project: rammearkitektur/gitlab-ci-templates
    file: templates/poetry-precommit.yml


# ---------------------------------------------------------------------------
# Lint
# ---------------------------------------------------------------------------
Lint Python:
  extends: .lint-python
  stage: lint
  script:
    - poetry run pre-commit run --all-files


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------
.test-template: &test
  extends: .test-python
  stage: test
  needs: []

Test on Python 3.9:
  <<: *test
  image: python:3.9

Test on Python 3.10:
  <<: *test
  image: python:3.10


# ---------------------------------------------------------------------------
# Release
# ---------------------------------------------------------------------------
Release to PyPI:
  extends: .install-deps
  image: python:3.9
  stage: release
  rules:
    # Matches <version core> from SemVer 2.0.0 BNF grammar. Ex. 2.3.4, but not 2.3.4-rc
    - if: $CI_COMMIT_TAG =~ /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
  script: poetry publish --build -u OS2mo -p $PYPI_PWD
